// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vertex.proto

package com.lsdb.store.serialization;

public final class VertexProto {
  private VertexProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface VertexOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Vertex)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string label = 2;</code>
     */
    java.lang.String getLabel();
    /**
     * <code>string label = 2;</code>
     */
    com.google.protobuf.ByteString
        getLabelBytes();

    /**
     * <code>map&lt;string, string&gt; properties = 3;</code>
     */
    int getPropertiesCount();
    /**
     * <code>map&lt;string, string&gt; properties = 3;</code>
     */
    boolean containsProperties(
        java.lang.String key);
    /**
     * Use {@link #getPropertiesMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getProperties();
    /**
     * <code>map&lt;string, string&gt; properties = 3;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getPropertiesMap();
    /**
     * <code>map&lt;string, string&gt; properties = 3;</code>
     */

    java.lang.String getPropertiesOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; properties = 3;</code>
     */

    java.lang.String getPropertiesOrThrow(
        java.lang.String key);

    /**
     * <code>repeated string incomingEdgeIds = 4;</code>
     */
    java.util.List<java.lang.String>
        getIncomingEdgeIdsList();
    /**
     * <code>repeated string incomingEdgeIds = 4;</code>
     */
    int getIncomingEdgeIdsCount();
    /**
     * <code>repeated string incomingEdgeIds = 4;</code>
     */
    java.lang.String getIncomingEdgeIds(int index);
    /**
     * <code>repeated string incomingEdgeIds = 4;</code>
     */
    com.google.protobuf.ByteString
        getIncomingEdgeIdsBytes(int index);

    /**
     * <code>repeated string outgoingEdgeIds = 5;</code>
     */
    java.util.List<java.lang.String>
        getOutgoingEdgeIdsList();
    /**
     * <code>repeated string outgoingEdgeIds = 5;</code>
     */
    int getOutgoingEdgeIdsCount();
    /**
     * <code>repeated string outgoingEdgeIds = 5;</code>
     */
    java.lang.String getOutgoingEdgeIds(int index);
    /**
     * <code>repeated string outgoingEdgeIds = 5;</code>
     */
    com.google.protobuf.ByteString
        getOutgoingEdgeIdsBytes(int index);
  }
  /**
   * Protobuf type {@code Vertex}
   */
  public  static final class Vertex extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Vertex)
      VertexOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Vertex.newBuilder() to construct.
    private Vertex(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Vertex() {
      id_ = "";
      label_ = "";
      incomingEdgeIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      outgoingEdgeIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Vertex(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              label_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                properties_ = com.google.protobuf.MapField.newMapField(
                    PropertiesDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000004;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              properties__ = input.readMessage(
                  PropertiesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              properties_.getMutableMap().put(
                  properties__.getKey(), properties__.getValue());
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                incomingEdgeIds_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              incomingEdgeIds_.add(s);
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                outgoingEdgeIds_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              outgoingEdgeIds_.add(s);
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          incomingEdgeIds_ = incomingEdgeIds_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          outgoingEdgeIds_ = outgoingEdgeIds_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lsdb.store.serialization.VertexProto.internal_static_Vertex_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetProperties();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lsdb.store.serialization.VertexProto.internal_static_Vertex_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lsdb.store.serialization.VertexProto.Vertex.class, com.lsdb.store.serialization.VertexProto.Vertex.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LABEL_FIELD_NUMBER = 2;
    private volatile java.lang.Object label_;
    /**
     * <code>string label = 2;</code>
     */
    public java.lang.String getLabel() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        label_ = s;
        return s;
      }
    }
    /**
     * <code>string label = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLabelBytes() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROPERTIES_FIELD_NUMBER = 3;
    private static final class PropertiesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.lsdb.store.serialization.VertexProto.internal_static_Vertex_PropertiesEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> properties_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetProperties() {
      if (properties_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            PropertiesDefaultEntryHolder.defaultEntry);
      }
      return properties_;
    }

    public int getPropertiesCount() {
      return internalGetProperties().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; properties = 3;</code>
     */

    public boolean containsProperties(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetProperties().getMap().containsKey(key);
    }
    /**
     * Use {@link #getPropertiesMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getProperties() {
      return getPropertiesMap();
    }
    /**
     * <code>map&lt;string, string&gt; properties = 3;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getPropertiesMap() {
      return internalGetProperties().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; properties = 3;</code>
     */

    public java.lang.String getPropertiesOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetProperties().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; properties = 3;</code>
     */

    public java.lang.String getPropertiesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetProperties().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int INCOMINGEDGEIDS_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList incomingEdgeIds_;
    /**
     * <code>repeated string incomingEdgeIds = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getIncomingEdgeIdsList() {
      return incomingEdgeIds_;
    }
    /**
     * <code>repeated string incomingEdgeIds = 4;</code>
     */
    public int getIncomingEdgeIdsCount() {
      return incomingEdgeIds_.size();
    }
    /**
     * <code>repeated string incomingEdgeIds = 4;</code>
     */
    public java.lang.String getIncomingEdgeIds(int index) {
      return incomingEdgeIds_.get(index);
    }
    /**
     * <code>repeated string incomingEdgeIds = 4;</code>
     */
    public com.google.protobuf.ByteString
        getIncomingEdgeIdsBytes(int index) {
      return incomingEdgeIds_.getByteString(index);
    }

    public static final int OUTGOINGEDGEIDS_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList outgoingEdgeIds_;
    /**
     * <code>repeated string outgoingEdgeIds = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getOutgoingEdgeIdsList() {
      return outgoingEdgeIds_;
    }
    /**
     * <code>repeated string outgoingEdgeIds = 5;</code>
     */
    public int getOutgoingEdgeIdsCount() {
      return outgoingEdgeIds_.size();
    }
    /**
     * <code>repeated string outgoingEdgeIds = 5;</code>
     */
    public java.lang.String getOutgoingEdgeIds(int index) {
      return outgoingEdgeIds_.get(index);
    }
    /**
     * <code>repeated string outgoingEdgeIds = 5;</code>
     */
    public com.google.protobuf.ByteString
        getOutgoingEdgeIdsBytes(int index) {
      return outgoingEdgeIds_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getLabelBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, label_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetProperties(),
          PropertiesDefaultEntryHolder.defaultEntry,
          3);
      for (int i = 0; i < incomingEdgeIds_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, incomingEdgeIds_.getRaw(i));
      }
      for (int i = 0; i < outgoingEdgeIds_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, outgoingEdgeIds_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getLabelBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, label_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetProperties().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        properties__ = PropertiesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, properties__);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < incomingEdgeIds_.size(); i++) {
          dataSize += computeStringSizeNoTag(incomingEdgeIds_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getIncomingEdgeIdsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < outgoingEdgeIds_.size(); i++) {
          dataSize += computeStringSizeNoTag(outgoingEdgeIds_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getOutgoingEdgeIdsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.lsdb.store.serialization.VertexProto.Vertex)) {
        return super.equals(obj);
      }
      com.lsdb.store.serialization.VertexProto.Vertex other = (com.lsdb.store.serialization.VertexProto.Vertex) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && getLabel()
          .equals(other.getLabel());
      result = result && internalGetProperties().equals(
          other.internalGetProperties());
      result = result && getIncomingEdgeIdsList()
          .equals(other.getIncomingEdgeIdsList());
      result = result && getOutgoingEdgeIdsList()
          .equals(other.getOutgoingEdgeIdsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + LABEL_FIELD_NUMBER;
      hash = (53 * hash) + getLabel().hashCode();
      if (!internalGetProperties().getMap().isEmpty()) {
        hash = (37 * hash) + PROPERTIES_FIELD_NUMBER;
        hash = (53 * hash) + internalGetProperties().hashCode();
      }
      if (getIncomingEdgeIdsCount() > 0) {
        hash = (37 * hash) + INCOMINGEDGEIDS_FIELD_NUMBER;
        hash = (53 * hash) + getIncomingEdgeIdsList().hashCode();
      }
      if (getOutgoingEdgeIdsCount() > 0) {
        hash = (37 * hash) + OUTGOINGEDGEIDS_FIELD_NUMBER;
        hash = (53 * hash) + getOutgoingEdgeIdsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lsdb.store.serialization.VertexProto.Vertex parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lsdb.store.serialization.VertexProto.Vertex parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lsdb.store.serialization.VertexProto.Vertex parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lsdb.store.serialization.VertexProto.Vertex parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lsdb.store.serialization.VertexProto.Vertex parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lsdb.store.serialization.VertexProto.Vertex parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lsdb.store.serialization.VertexProto.Vertex parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lsdb.store.serialization.VertexProto.Vertex parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lsdb.store.serialization.VertexProto.Vertex parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.lsdb.store.serialization.VertexProto.Vertex parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lsdb.store.serialization.VertexProto.Vertex parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lsdb.store.serialization.VertexProto.Vertex parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lsdb.store.serialization.VertexProto.Vertex prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Vertex}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Vertex)
        com.lsdb.store.serialization.VertexProto.VertexOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lsdb.store.serialization.VertexProto.internal_static_Vertex_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetProperties();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetMutableProperties();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lsdb.store.serialization.VertexProto.internal_static_Vertex_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lsdb.store.serialization.VertexProto.Vertex.class, com.lsdb.store.serialization.VertexProto.Vertex.Builder.class);
      }

      // Construct using com.pkdb.store.serialization.VertexProto.Vertex.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        label_ = "";

        internalGetMutableProperties().clear();
        incomingEdgeIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        outgoingEdgeIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lsdb.store.serialization.VertexProto.internal_static_Vertex_descriptor;
      }

      @java.lang.Override
      public com.lsdb.store.serialization.VertexProto.Vertex getDefaultInstanceForType() {
        return com.lsdb.store.serialization.VertexProto.Vertex.getDefaultInstance();
      }

      @java.lang.Override
      public com.lsdb.store.serialization.VertexProto.Vertex build() {
        com.lsdb.store.serialization.VertexProto.Vertex result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.lsdb.store.serialization.VertexProto.Vertex buildPartial() {
        com.lsdb.store.serialization.VertexProto.Vertex result = new com.lsdb.store.serialization.VertexProto.Vertex(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.label_ = label_;
        result.properties_ = internalGetProperties();
        result.properties_.makeImmutable();
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          incomingEdgeIds_ = incomingEdgeIds_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.incomingEdgeIds_ = incomingEdgeIds_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          outgoingEdgeIds_ = outgoingEdgeIds_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.outgoingEdgeIds_ = outgoingEdgeIds_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lsdb.store.serialization.VertexProto.Vertex) {
          return mergeFrom((com.lsdb.store.serialization.VertexProto.Vertex)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lsdb.store.serialization.VertexProto.Vertex other) {
        if (other == com.lsdb.store.serialization.VertexProto.Vertex.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getLabel().isEmpty()) {
          label_ = other.label_;
          onChanged();
        }
        internalGetMutableProperties().mergeFrom(
            other.internalGetProperties());
        if (!other.incomingEdgeIds_.isEmpty()) {
          if (incomingEdgeIds_.isEmpty()) {
            incomingEdgeIds_ = other.incomingEdgeIds_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureIncomingEdgeIdsIsMutable();
            incomingEdgeIds_.addAll(other.incomingEdgeIds_);
          }
          onChanged();
        }
        if (!other.outgoingEdgeIds_.isEmpty()) {
          if (outgoingEdgeIds_.isEmpty()) {
            outgoingEdgeIds_ = other.outgoingEdgeIds_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureOutgoingEdgeIdsIsMutable();
            outgoingEdgeIds_.addAll(other.outgoingEdgeIds_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lsdb.store.serialization.VertexProto.Vertex parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lsdb.store.serialization.VertexProto.Vertex) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object label_ = "";
      /**
       * <code>string label = 2;</code>
       */
      public java.lang.String getLabel() {
        java.lang.Object ref = label_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          label_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string label = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLabelBytes() {
        java.lang.Object ref = label_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          label_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string label = 2;</code>
       */
      public Builder setLabel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        label_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string label = 2;</code>
       */
      public Builder clearLabel() {
        
        label_ = getDefaultInstance().getLabel();
        onChanged();
        return this;
      }
      /**
       * <code>string label = 2;</code>
       */
      public Builder setLabelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        label_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> properties_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetProperties() {
        if (properties_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              PropertiesDefaultEntryHolder.defaultEntry);
        }
        return properties_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableProperties() {
        onChanged();;
        if (properties_ == null) {
          properties_ = com.google.protobuf.MapField.newMapField(
              PropertiesDefaultEntryHolder.defaultEntry);
        }
        if (!properties_.isMutable()) {
          properties_ = properties_.copy();
        }
        return properties_;
      }

      public int getPropertiesCount() {
        return internalGetProperties().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; properties = 3;</code>
       */

      public boolean containsProperties(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetProperties().getMap().containsKey(key);
      }
      /**
       * Use {@link #getPropertiesMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getProperties() {
        return getPropertiesMap();
      }
      /**
       * <code>map&lt;string, string&gt; properties = 3;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getPropertiesMap() {
        return internalGetProperties().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; properties = 3;</code>
       */

      public java.lang.String getPropertiesOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetProperties().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; properties = 3;</code>
       */

      public java.lang.String getPropertiesOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetProperties().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearProperties() {
        internalGetMutableProperties().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; properties = 3;</code>
       */

      public Builder removeProperties(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableProperties().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableProperties() {
        return internalGetMutableProperties().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; properties = 3;</code>
       */
      public Builder putProperties(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableProperties().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; properties = 3;</code>
       */

      public Builder putAllProperties(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableProperties().getMutableMap()
            .putAll(values);
        return this;
      }

      private com.google.protobuf.LazyStringList incomingEdgeIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureIncomingEdgeIdsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          incomingEdgeIds_ = new com.google.protobuf.LazyStringArrayList(incomingEdgeIds_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string incomingEdgeIds = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getIncomingEdgeIdsList() {
        return incomingEdgeIds_.getUnmodifiableView();
      }
      /**
       * <code>repeated string incomingEdgeIds = 4;</code>
       */
      public int getIncomingEdgeIdsCount() {
        return incomingEdgeIds_.size();
      }
      /**
       * <code>repeated string incomingEdgeIds = 4;</code>
       */
      public java.lang.String getIncomingEdgeIds(int index) {
        return incomingEdgeIds_.get(index);
      }
      /**
       * <code>repeated string incomingEdgeIds = 4;</code>
       */
      public com.google.protobuf.ByteString
          getIncomingEdgeIdsBytes(int index) {
        return incomingEdgeIds_.getByteString(index);
      }
      /**
       * <code>repeated string incomingEdgeIds = 4;</code>
       */
      public Builder setIncomingEdgeIds(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIncomingEdgeIdsIsMutable();
        incomingEdgeIds_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string incomingEdgeIds = 4;</code>
       */
      public Builder addIncomingEdgeIds(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIncomingEdgeIdsIsMutable();
        incomingEdgeIds_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string incomingEdgeIds = 4;</code>
       */
      public Builder addAllIncomingEdgeIds(
          java.lang.Iterable<java.lang.String> values) {
        ensureIncomingEdgeIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, incomingEdgeIds_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string incomingEdgeIds = 4;</code>
       */
      public Builder clearIncomingEdgeIds() {
        incomingEdgeIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string incomingEdgeIds = 4;</code>
       */
      public Builder addIncomingEdgeIdsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureIncomingEdgeIdsIsMutable();
        incomingEdgeIds_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList outgoingEdgeIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureOutgoingEdgeIdsIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          outgoingEdgeIds_ = new com.google.protobuf.LazyStringArrayList(outgoingEdgeIds_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated string outgoingEdgeIds = 5;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getOutgoingEdgeIdsList() {
        return outgoingEdgeIds_.getUnmodifiableView();
      }
      /**
       * <code>repeated string outgoingEdgeIds = 5;</code>
       */
      public int getOutgoingEdgeIdsCount() {
        return outgoingEdgeIds_.size();
      }
      /**
       * <code>repeated string outgoingEdgeIds = 5;</code>
       */
      public java.lang.String getOutgoingEdgeIds(int index) {
        return outgoingEdgeIds_.get(index);
      }
      /**
       * <code>repeated string outgoingEdgeIds = 5;</code>
       */
      public com.google.protobuf.ByteString
          getOutgoingEdgeIdsBytes(int index) {
        return outgoingEdgeIds_.getByteString(index);
      }
      /**
       * <code>repeated string outgoingEdgeIds = 5;</code>
       */
      public Builder setOutgoingEdgeIds(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureOutgoingEdgeIdsIsMutable();
        outgoingEdgeIds_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string outgoingEdgeIds = 5;</code>
       */
      public Builder addOutgoingEdgeIds(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureOutgoingEdgeIdsIsMutable();
        outgoingEdgeIds_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string outgoingEdgeIds = 5;</code>
       */
      public Builder addAllOutgoingEdgeIds(
          java.lang.Iterable<java.lang.String> values) {
        ensureOutgoingEdgeIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, outgoingEdgeIds_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string outgoingEdgeIds = 5;</code>
       */
      public Builder clearOutgoingEdgeIds() {
        outgoingEdgeIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string outgoingEdgeIds = 5;</code>
       */
      public Builder addOutgoingEdgeIdsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureOutgoingEdgeIdsIsMutable();
        outgoingEdgeIds_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Vertex)
    }

    // @@protoc_insertion_point(class_scope:Vertex)
    private static final com.lsdb.store.serialization.VertexProto.Vertex DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lsdb.store.serialization.VertexProto.Vertex();
    }

    public static com.lsdb.store.serialization.VertexProto.Vertex getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Vertex>
        PARSER = new com.google.protobuf.AbstractParser<Vertex>() {
      @java.lang.Override
      public Vertex parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Vertex(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Vertex> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Vertex> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.lsdb.store.serialization.VertexProto.Vertex getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Vertex_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Vertex_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Vertex_PropertiesEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Vertex_PropertiesEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014vertex.proto\"\265\001\n\006Vertex\022\n\n\002id\030\001 \001(\t\022\r\n" +
      "\005label\030\002 \001(\t\022+\n\nproperties\030\003 \003(\0132\027.Verte" +
      "x.PropertiesEntry\022\027\n\017incomingEdgeIds\030\004 \003" +
      "(\t\022\027\n\017outgoingEdgeIds\030\005 \003(\t\0321\n\017Propertie" +
      "sEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001B+" +
      "\n\034com.pkdb.store.serializationB\013VertexPr" +
      "otob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Vertex_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Vertex_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Vertex_descriptor,
        new java.lang.String[] { "Id", "Label", "Properties", "IncomingEdgeIds", "OutgoingEdgeIds", });
    internal_static_Vertex_PropertiesEntry_descriptor =
      internal_static_Vertex_descriptor.getNestedTypes().get(0);
    internal_static_Vertex_PropertiesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Vertex_PropertiesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
